datapath: '/Users/joseperezcano/desktop/IDAO_2022/data/dichalcogenides_public'
test_datapath: '/Users/joseperezcano/desktop/IDAO_2022/data/dichalcogenides_private'
checkpoint_path: 'None'

model:
  epochs: 200
  batch_size: 32
  lr: 1e-4 
  cutoff: 4


